//
//  UIImagePickerController+Private.h
//  SurfVideo
//
//  Created by Jinwoo Kim on 5/8/24.
//

#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

UIKIT_EXTERN BOOL UIImagePickerLoadPhotoLibraryIfNecessary(void);

UIKIT_EXTERN UIImagePickerControllerInfoKey const UIImagePickerControllerAllowsEditing;
UIKIT_EXTERN UIImagePickerControllerInfoKey const UIImagePickerControllerVideoQuality;
UIKIT_EXTERN UIImagePickerControllerInfoKey const UIImagePickerControllerVideoMaximumDuration;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerFullScreenImage;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerOriginalImageData;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerDebugSidecarFileURLs;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerVideoEditingStart;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerVideoEditingEnd;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerDisableTrimVideoMessage;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerVideoRemakerQuality;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerAllowMultipleSelection;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerMultipleSelectionLimit;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerRequiresPickingConfirmation;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerShowsFileSizePicker;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerOnlyShowAutoloopVideos;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerConvertAutoloopsToGIF;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerShowsPrompt;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerStaticPrompt;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerTargetForPrompt;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerUseTelephonyUI;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerAllowVideoEditing;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerVideoCaptureMaximumDuration;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerHidesPlaceholderNavigationBar;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerShowCameraControls;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerCameraViewTransform;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerCameraOverlayView;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerCameraDevice;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerCameraCaptureMode;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerCameraFlashMode;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerVideoDontTranscode;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerViewImageBeforeSelecting;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerReviewCapturedItem;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerAllowAnySuperview;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerForceNativeScreenScale;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerController1XCroppedImage;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerEditabilityChangedNotification;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerUserDidCaptureItemNotification;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerUserDidRejectItemNotification;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerAllowStillDuringVideo;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerChooseButtonTitle;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerCancelButtonTitle;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerCustomBackgroundColor;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerMaxZoomScaleOverride;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerAllowIris;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerIrisVideoFileURL;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerMediaTypes;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerSavingOptions;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerSourceType;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerTemporaryDirectoryUrl;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerAutoloopGIFURL;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerPHAssetLocalIdentifier;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerImageURLExportPreset;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerViewWidth;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerViewHeight;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIImagePickerControllerModalPresentationStyle;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIVideoEditorControllerVideoPath;
UIKIT_EXTERN UIImagePickerControllerInfoKey const _UIVideoEditorControllerVideoURL;

NS_ASSUME_NONNULL_END
